### ISSUE TITLE
model.py  ，the program have a small error！

### ISSUE THREAD

**Issue by gmt710** [LeMinhThong/blackbox-attack#2]
model.py   

line 469:
change 
test(net, test_loader) ----->test_mnist(net, test_loader).

line 369:
change 
test_minst(net, test_loader) ----->test_mnist(net, test_loader).

maybe error 2 need not to change.It is just a suggestion.
Thanks very much for your sharing your code about black-box adversarial examples.you know that the sharing about black-box adversarial examples is rarely.I also have some questions about the framework Pythorch  you used  that is only  deployed in linux？I deploy the code in my windows,and still have an error “cuda runtime error (48) : no kernel image is available for execution on the device at”，I do not find an useful suggestion  for me to solve this troublesome problem.
I will look forward to your reply very much.

**Comment by cmhcbb** [comment]
Yes. You are 100% right. But it is for testing the model you have just trained or got.
