### ISSUE TITLE
Is the black-box attack is the code corresponding to OptAttack?

### ISSUE THREAD

**Issue by fiona-lxd** [LeMinhThong/blackbox-attack#5]
Hi, is the black-box attack is the code corresponding to OptAttack in paper QUERY-EFFICIENT HARD-LABEL BLACK-BOX ATTACK: AN OPTIMIZATION-BASED APPROACH published on ICLR2019?

**Comment by cmhcbb** [comment]
Yes, you could also find the updated SignOPT and the numpy version in https://github.com/cmhcbb/attackbox.

**Comment by fiona-lxd** [comment]
Ok. Thank you a lot for your reply.
